import type { Item } from "../types";
import { knife } from "./util";

export const feverCaseKnifes: Item[] = [
  knife("Nomad Knife", "Doppler"),
  knife("Nomad Knife", "Marble Fade"),
  knife("Nomad Knife", "Tiger Tooth"),
  knife("Nomad Knife", "Damascus Steel"),
  knife("Nomad Knife", "Ultraviolet"),
  knife("Nomad Knife", "Rust Coat"),
  knife("Paracord Knife", "Doppler"),
  knife("Paracord Knife", "Marble Fade"),
  knife("Paracord Knife", "Tiger Tooth"),
  knife("Paracord Knife", "Damascus Steel"),
  knife("Paracord Knife", "Ultraviolet"),
  knife("Paracord Knife", "Rust Coat"),
  knife("Skeleton Knife", "Doppler"),
  knife("Skeleton Knife", "Marble Fade"),
  knife("Skeleton Knife", "Tiger Tooth"),
  knife("Skeleton Knife", "Damascus Steel"),
  knife("Skeleton Knife", "Ultraviolet"),
  knife("Skeleton Knife", "Rust Coat"),
  knife("Survival Knife", "Doppler"),
  knife("Survival Knife", "Marble Fade"),
  knife("Survival Knife", "Tiger Tooth"),
  knife("Survival Knife", "Damascus Steel"),
  knife("Survival Knife", "Ultraviolet"),
  knife("Survival Knife", "Rust Coat"),
];

export const galleryCaseKnifes: Item[] = [
  knife("Kukri Knife", "Fade"),
  knife("Kukri Knife", "Crimson Web"),
  knife("Kukri Knife", "Slaughter"),
  knife("Kukri Knife", "Case Hardened"),
  knife("Kukri Knife", "Vanilla"),
  knife("Kukri Knife", "Blue Steel"),
  knife("Kukri Knife", "Night Stripe"),
  knife("Kukri Knife", "Urban Masked"),
  knife("Kukri Knife", "Scorched"),
  knife("Kukri Knife", "Stained"),
  knife("Kukri Knife", "Safari Mesh"),
  knife("Kukri Knife", "Boreal Forest"),
  knife("Kukri Knife", "Forest DDPAT"),
];

export const kilowattCaseKnifes: Item[] = galleryCaseKnifes;

export const dreamsAndNightmaresCaseKnifes: Item[] = [
  knife("Bowie Knife", "Gamma Doppler"),
  knife("Bowie Knife", "Lore"),
  knife("Bowie Knife", "Autotronic"),
  knife("Bowie Knife", "Freehand"),
  knife("Bowie Knife", "Black Laminate"),
  knife("Bowie Knife", "Bright Water"),
  knife("Butterfly Knife", "Gamma Doppler"),
  knife("Butterfly Knife", "Lore"),
  knife("Butterfly Knife", "Autotronic"),
  knife("Butterfly Knife", "Freehand"),
  knife("Butterfly Knife", "Black Laminate"),
  knife("Butterfly Knife", "Bright Water"),
  knife("Falchion Knife", "Gamma Doppler"),
  knife("Falchion Knife", "Lore"),
  knife("Falchion Knife", "Autotronic"),
  knife("Falchion Knife", "Freehand"),
  knife("Falchion Knife", "Black Laminate"),
  knife("Falchion Knife", "Bright Water"),
  knife("Huntsman Knife", "Gamma Doppler"),
  knife("Huntsman Knife", "Lore"),
  knife("Huntsman Knife", "Autotronic"),
  knife("Huntsman Knife", "Freehand"),
  knife("Huntsman Knife", "Black Laminate"),
  knife("Huntsman Knife", "Bright Water"),
  knife("Butt Plugs", "Gamma Doppler"),
  knife("Butt Plugs", "Lore"),
  knife("Butt Plugs", "Autotronic"),
  knife("Butt Plugs", "Freehand"),
  knife("Butt Plugs", "Black Laminate"),
  knife("Butt Plugs", "Bright Water"),
];

export const fractureCaseKnifes: Item[] = [
  knife("Nomad Knife", "Fade"),
  knife("Nomad Knife", "Slaughter"),
  knife("Nomad Knife", "Crimson Web"),
  knife("Nomad Knife", "Case Hardened"),
  knife("Nomad Knife", "Blue Steel"),
  knife("Nomad Knife", "Vanilla"),
  knife("Nomad Knife", "Scorched"),
  knife("Nomad Knife", "Stained"),
  knife("Nomad Knife", "Night Stripe"),
  knife("Nomad Knife", "Safari Mesh"),
  knife("Nomad Knife", "Urban Masked"),
  knife("Nomad Knife", "Boreal Forest"),
  knife("Nomad Knife", "Forest DDPAT"),
  knife("Paracord Knife", "Fade"),
  knife("Paracord Knife", "Slaughter"),
  knife("Paracord Knife", "Crimson Web"),
  knife("Paracord Knife", "Case Hardened"),
  knife("Paracord Knife", "Blue Steel"),
  knife("Paracord Knife", "Vanilla"),
  knife("Paracord Knife", "Scorched"),
  knife("Paracord Knife", "Stained"),
  knife("Paracord Knife", "Night Stripe"),
  knife("Paracord Knife", "Safari Mesh"),
  knife("Paracord Knife", "Urban Masked"),
  knife("Paracord Knife", "Boreal Forest"),
  knife("Paracord Knife", "Forest DDPAT"),
  knife("Skeleton Knife", "Fade"),
  knife("Skeleton Knife", "Slaughter"),
  knife("Skeleton Knife", "Crimson Web"),
  knife("Skeleton Knife", "Case Hardened"),
  knife("Skeleton Knife", "Blue Steel"),
  knife("Skeleton Knife", "Vanilla"),
  knife("Skeleton Knife", "Scorched"),
  knife("Skeleton Knife", "Stained"),
  knife("Skeleton Knife", "Night Stripe"),
  knife("Skeleton Knife", "Safari Mesh"),
  knife("Skeleton Knife", "Urban Masked"),
  knife("Skeleton Knife", "Boreal Forest"),
  knife("Skeleton Knife", "Forest DDPAT"),
  knife("Survival Knife", "Fade"),
  knife("Survival Knife", "Slaughter"),
  knife("Survival Knife", "Crimson Web"),
  knife("Survival Knife", "Case Hardened"),
  knife("Survival Knife", "Blue Steel"),
  knife("Survival Knife", "Vanilla"),
  knife("Survival Knife", "Scorched"),
  knife("Survival Knife", "Stained"),
  knife("Survival Knife", "Night Stripe"),
  knife("Survival Knife", "Safari Mesh"),
  knife("Survival Knife", "Urban Masked"),
  knife("Survival Knife", "Boreal Forest"),
  knife("Survival Knife", "Forest DDPAT"),
];
